#ifndef STATISTIC_DEFINITIONS_H
#define STATISTIC_DEFINITIONS_H

#include "device.h"

#ifdef MACBOOK
#define STATISTIC_MAX_THREADS_PER_MULTIPROCESSOR 2048
#define STATISTIC_MULTIPROCESSORS 2
#define STATISTIC_BLOCKSIZE_STEPSIZE 32
#define STATISTIC_MAX_GRIDSIZE 192
#define STATISTIC_MAX_BLOCKSIZE 1024
#endif

#ifdef XMG
#define STATISTIC_MAX_THREADS_PER_MULTIPROCESSOR 1536
#define STATISTIC_MULTIPROCESSORS 3
#define STATISTIC_BLOCKSIZE_STEPSIZE 16
#define STATISTIC_MAX_GRIDSIZE 192
#define STATISTIC_MAX_BLOCKSIZE 768
#endif

#ifdef GTX780
#define STATISTIC_MAX_THREADS_PER_MULTIPROCESSOR 2048
#define STATISTIC_MULTIPROCESSORS 12
#define STATISTIC_BLOCKSIZE_STEPSIZE 32
#define STATISTIC_MAX_GRIDSIZE 192
#define STATISTIC_MAX_BLOCKSIZE 1024
#endif

#endif
