#ifndef STATISTIC_DEFINITIONS_H
#define STATISTIC_DEFINITIONS_H

#include "device.h"

#ifdef MACBOOK
#define STATISTIC_MAX_THREADS (16*640)
#define STATISTIC_GRIDSIZE_MULTIPLIER 2
#define STATISTIC_BLOCKSIZE_STEPSIZE 32
#define STATISTIC_MAX_GRIDSIZE 1024
#define STATISTIC_MAX_BLOCKSIZE 1024
#endif

#ifdef XMG
#define STATISTIC_MAX_THREADS (8*640)
#define STATISTIC_GRIDSIZE_MULTIPLIER 3
#define STATISTIC_BLOCKSIZE_STEPSIZE 16
#define STATISTIC_MAX_GRIDSIZE 1024
#define STATISTIC_MAX_BLOCKSIZE 1024
#endif

#endif
